apiVersion: forge.agentforge.dev/v1alpha1
kind: AgentCard
metadata:
  labels:
    app.kubernetes.io/name: agent-forge-operator
    app.kubernetes.io/managed-by: kustomize
  name: agentcard-sample
spec:
  # TODO(user): Add fields here
