apiVersion: forge.agentforge.dev/v1alpha1
kind: TaskPipeline
metadata:
  labels:
    app.kubernetes.io/name: agent-forge-operator
    app.kubernetes.io/managed-by: kustomize
  name: taskpipeline-sample
spec:
  # TODO(user): Add fields here
