## Append samples of your project ##
resources:
- daedalus_v1alpha1_agentruntime.yaml
- daedalus_v1alpha1_agentruntime_byo.yaml
- daedalus_v1alpha1_modelconfig.yaml
- daedalus_v1alpha1_modelconfig_openai.yaml
- daedalus_v1alpha1_mcpserver.yaml
- daedalus_v1alpha1_taskpipeline.yaml
- daedalus_v1alpha1_agentcard.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
